services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onoffice-sdk
    volumes:
      - .:/app
    working_dir: /app
    environment:
      MEMORY_LIMIT: -1
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_START_WITH_REQUEST: yes
      PHP_IDE_CONFIG: serverName=onoffice-sdk
    extra_hosts:
      - "host.docker.internal:host-gateway"
