<?php

declare(strict_types=1);

namespace BytesCommerce\OnOffice\Attributes\Enum;

enum BundeslandEnum: string
{
    case ABRUZZEN = 'Abruzzen';
    case AOSTATAL = 'Aostatal';
    case APULIEN = 'Apulien';
    case BASILIKATA = 'Basilikata';
    case EMILIA_ROMAGNA = 'Emilia-Romagna';
    case FRIAUL_JULISCH_VENETIEN = 'Friaul-Julisch Venetien';
    case KALABRIEN = 'Kalabrien';
    case KAMPANIEN = 'Kampanien';
    case LATIUM = 'Latium';
    case LIGURIEN = 'Ligurien';
    case LOMBARDEI = 'Lombardei';
    case MARKEN = 'Marken';
    case MOLISE = 'Molise';
    case PIEMONT = 'Piemont';
    case SARDINIEN = 'Sardinien';
    case SIZILIEN = 'Sizilien';
    case TOSKANA = 'Toskana';
    case TRENTINO_SUEDTIROL = 'Trentino-Südtirol';
    case UMBRIEN = 'Umbrien';
    case VENETIEN = 'Venetien';
    case EXTREMADURA = 'Extremadura';
    case KASTILIEN_LA_MANCHA = 'Kastilien_La_Mancha';
    case KANARISCHE_INSELN = 'Kanarische_Inseln';
    case GALICIEN = 'Galicien';
    case KATALONIEN = 'Katalonien';
    case BASKENLAND = 'Baskenland';
    case BALEARISCHE_INSELN = 'Balearische_Inseln';
    case ASTURIEN = 'Asturien';
    case ARAGONIEN = 'Aragonien';
    case ANDALUSIEN = 'Andalusien';
    case KANTABRIEN = 'Kantabrien';
    case LA_RIOJA = 'La_Rioja';
    case MADRID = 'Madrid';
    case MURCIA = 'Murcia';
    case NAVARRA = 'Navarra';
    case VALENCIA = 'Valencia';
    case CEUTA = 'Ceuta';
    case MELILLA = 'Melilla';
    case KASTILIEN_LEON = 'Kastilien_Leon';
    case BAYERN = 'Bayern';
    case BRANDENBURG = 'Brandenburg';
    case BERLIN = 'Berlin';
    case BREMEN = 'Bremen';
    case BADEN_WUERTTEMBERG = 'Baden-Württemberg';
    case HESSEN = 'Hessen';
    case HAMBURG = 'Hamburg';
    case MECKLENBURG_VORPOMMERN = 'Mecklenburg-Vorpommern';
    case TESSIN = 'Tessin';
    case NIEDERSACHSEN = 'Niedersachsen';
    case NORDRHEIN_WESTFALEN = 'Nordrhein-Westfalen';
    case RHEINLAND_PFALZ = 'Rheinland-Pfalz';
    case SAARLAND = 'Saarland';
    case SACHSEN = 'Sachsen';
    case SACHSEN_ANHALT = 'Sachsen-Anhalt';
    case SCHLESWIG_HOLSTEIN = 'Schleswig-Holstein';
    case THUERINGEN = 'Thüringen';
    case BURGENLAND = 'Burgenland';
    case KAERNTEN = 'Kärnten';
    case NIEDEROESTERREICH = 'Niederösterreich';
    case OBEROESTERREICH = 'Oberösterreich';
    case SALZBURG = 'Salzburg';
    case STEIERMARK = 'Steiermark';
    case TIROL = 'Tirol';
    case VORARLBERG = 'Vorarlberg';
    case WIEN = 'Wien';
    case AARGAU = 'Aargau';
    case APPENZELL_AUSSERRHODEN = 'Appenzell Ausserrhoden';
    case APPENZELL_INNERRHODEN = 'Appenzell Innerrhoden';
    case BASEL_LANDSCHAFT = 'Basel-Landschaft';
    case BASEL_STADT = 'Basel-Stadt';
    case BERN = 'Bern';
    case FREIBURG = 'Freiburg';
    case GENF = 'Genf';
    case GLARUS = 'Glarus';
    case GRAUBUENDEN = 'Graubünden';
    case JURA = 'Jura';
    case LUZERN = 'Luzern';
    case NEUENBURG = 'Neuenburg';
    case NIDWALDEN = 'Nidwalden';
    case OBWALDEN = 'Obwalden';
    case SCHAFFHAUSEN = 'Schaffhausen';
    case SCHWYZ = 'Schwyz';
    case ST_GALLEN = 'St. Gallen';
    case SOLOTHURN = 'Solothurn';
    case THURGAU = 'Thurgau';
    case URI = 'Uri';
    case WALLIS = 'Wallis';
    case WAADT = 'Waadt';
    case ZUG = 'Zug';
    case ZUERICH = 'Zürich';
    case AUVERGNE_RHONE_ALPES = 'Auvergne-Rhône-Alpes';
    case BOURGOGNE_FRANCHE_COMTE = 'Bourgogne-Franche-Comté';
    case BRETAGNE = 'Bretagne';
    case CENTRE_VAL_DE_LOIRE = 'Centre-Val de Loire';
    case GRAND_EST = 'Grand Est';
    case HAUTS_DE_FRANCE = 'Hauts-de-France';
    case KORSIKA = 'Korsika';
    case NORMANDIE = 'Normandie';
    case NOUVELLE_AQUITAINE = 'Nouvelle-Aquitaine';
    case OKZITANIEN = 'Okzitanien';
    case PAYS_DE_LA_LOIRE = 'Pays de la Loire';
    case PROVENCE_ALPES_COTE_D_AZUR = 'Provence-Alpes-Côte d\'Azur';
    case ILE_DE_FRANCE = 'Île-de-France';
    case EAST_MIDLANDS = 'East Midlands';
    case EAST_OF_ENGLAND = 'East of England';
    case LONDON = 'London';
    case NORTH_EAST_ENGLAND = 'North East England';
    case NORTH_WEST_ENGLAND = 'North West England';
    case NORTHERN_IRELAND = 'Northern Ireland';
    case SCOTLAND = 'Scotland';
    case SOUTH_EAST_ENGLAND = 'South East England';
    case SOUTH_WEST_ENGLAND = 'South West England';
    case WALES = 'Wales';
    case WEST_MIDLANDS = 'West Midlands';
    case YORKSHIRE_AND_THE_HUMBER = 'Yorkshire and the Humber';
    case AVEIRO = 'Aveiro';
    case BEJA = 'Beja';
    case BRAGA = 'Braga';
    case BRAGANCA = 'Bragança';
    case CASTELO_BRANCO = 'Castelo Branco';
    case COIMBRA = 'Coimbra';
    case FARO = 'Faro';
    case GUARDA = 'Guarda';
    case LEIRIA = 'Leiria';
    case LISBOA = 'Lisboa';
    case PORTALEGRE = 'Portalegre';
    case PORTO = 'Porto';
    case SANTAREM = 'Santarém';
    case SETUBAL = 'Setúbal';
    case VIANA_DO_CASTELO = 'Viana do Castelo';
    case VILA_REAL = 'Vila Real';
    case VISEU = 'Viseu';
    case EVORA = 'Évora';
    case BJELOVAR_BILOGORA = 'Bjelovar-Bilogora';
    case BROD_POSAVINA = 'Brod-Posavina';
    case DUBROVNIK_NERETVA = 'Dubrovnik-Neretva';
    case ISTRIEN = 'Istrien';
    case KARLOVAC = 'Karlovac';
    case KOPRIVNICA_KRIZEVCI = 'Koprivnica-Krizevci';
    case KRAPINA_ZAGORJE = 'Krapina-Zagorje';
    case LIKA_SENJ = 'Lika-Senj';
    case MEDIMURJE = 'Međimurje';
    case OSIJEK_BARANJA = 'Osijek-Baranja';
    case POZEGA_SLAWONIEN = 'Požega-Slawonien';
    case PRIMORJE_GORSKI_KOTAR = 'Primorje-Gorski kotar';
    case SISAK_MOSLAVINA = 'Sisak-Moslavina';
    case SPLIT_DALMATIEN = 'Split-Dalmatien';
    case SIBENIK_KNIN = 'Šibenik-Knin';
    case VARAZDIN = 'Varazdin';
    case VIROVITICA_PODRAVINA = 'Virovitica-Podravina';
    case VUKOVAR_SYRMIEN = 'Vukovar-Syrmien';
    case ZADAR = 'Zadar';
    case ZAGREB = 'Zagreb';
    case STADT_ZAGREB = 'Stadt-Zagreb';

    public function label(): string
    {
        return match ($this) {
            self::ABRUZZEN => 'Abruzzen',
            self::AOSTATAL => 'Aostatal',
            self::APULIEN => 'Apulien',
            self::BASILIKATA => 'Basilikata',
            self::EMILIA_ROMAGNA => 'Emilia-Romagna',
            self::FRIAUL_JULISCH_VENETIEN => 'Friaul-Julisch Venetien',
            self::KALABRIEN => 'Kalabrien',
            self::KAMPANIEN => 'Kampanien',
            self::LATIUM => 'Latium',
            self::LIGURIEN => 'Ligurien',
            self::LOMBARDEI => 'Lombardei',
            self::MARKEN => 'Marken',
            self::MOLISE => 'Molise',
            self::PIEMONT => 'Piemont',
            self::SARDINIEN => 'Sardinien',
            self::SIZILIEN => 'Sizilien',
            self::TOSKANA => 'Toskana',
            self::TRENTINO_SUEDTIROL => 'Trentino-Südtirol',
            self::UMBRIEN => 'Umbrien',
            self::VENETIEN => 'Venetien',
            self::EXTREMADURA => 'Extramadura',
            self::KASTILIEN_LA_MANCHA => 'Kastilien-La Mancha',
            self::KANARISCHE_INSELN => 'Kanarische Inseln',
            self::GALICIEN => 'Galicien',
            self::KATALONIEN => 'Katalonien',
            self::BASKENLAND => 'Baskenland',
            self::BALEARISCHE_INSELN => 'Balearische Inseln',
            self::ASTURIEN => 'Asturien',
            self::ARAGONIEN => 'Aragonien',
            self::ANDALUSIEN => 'Andalusien',
            self::KANTABRIEN => 'Kantabrien',
            self::LA_RIOJA => 'La Rioja',
            self::MADRID => 'Madrid',
            self::MURCIA => 'Murcia',
            self::NAVARRA => 'Navarra',
            self::VALENCIA => 'Valencia',
            self::CEUTA => 'Ceuta',
            self::MELILLA => 'Melilla',
            self::KASTILIEN_LEON => 'Kastilien-León',
            self::BAYERN => 'Bayern',
            self::BRANDENBURG => 'Brandenburg',
            self::BERLIN => 'Berlin',
            self::BREMEN => 'Bremen',
            self::BADEN_WUERTTEMBERG => 'Baden-Württemberg',
            self::HESSEN => 'Hessen',
            self::HAMBURG => 'Hamburg',
            self::MECKLENBURG_VORPOMMERN => 'Mecklenburg-Vorpommern',
            self::TESSIN => 'Tessin',
            self::NIEDERSACHSEN => 'Niedersachsen',
            self::NORDRHEIN_WESTFALEN => 'Nordrhein-Westfalen',
            self::RHEINLAND_PFALZ => 'Rheinland-Pfalz',
            self::SAARLAND => 'Saarland',
            self::SACHSEN => 'Sachsen',
            self::SACHSEN_ANHALT => 'Sachsen-Anhalt',
            self::SCHLESWIG_HOLSTEIN => 'Schleswig-Holstein',
            self::THUERINGEN => 'Thüringen',
            self::BURGENLAND => 'Burgenland',
            self::KAERNTEN => 'Kärnten',
            self::NIEDEROESTERREICH => 'Niederösterreich',
            self::OBEROESTERREICH => 'Oberösterreich',
            self::SALZBURG => 'Salzburg',
            self::STEIERMARK => 'Steiermark',
            self::TIROL => 'Tirol',
            self::VORARLBERG => 'Vorarlberg',
            self::WIEN => 'Wien',
            self::AARGAU => 'Aargau',
            self::APPENZELL_AUSSERRHODEN => 'Appenzell Ausserrhoden',
            self::APPENZELL_INNERRHODEN => 'Appenzell Innerrhoden',
            self::BASEL_LANDSCHAFT => 'Basel-Landschaft',
            self::BASEL_STADT => 'Basel-Stadt',
            self::BERN => 'Bern',
            self::FREIBURG => 'Freiburg',
            self::GENF => 'Genf',
            self::GLARUS => 'Glarus',
            self::GRAUBUENDEN => 'Graubünden',
            self::JURA => 'Jura',
            self::LUZERN => 'Luzern',
            self::NEUENBURG => 'Neuenburg',
            self::NIDWALDEN => 'Nidwalden',
            self::OBWALDEN => 'Obwalden',
            self::SCHAFFHAUSEN => 'Schaffhausen',
            self::SCHWYZ => 'Schwyz',
            self::ST_GALLEN => 'St. Gallen',
            self::SOLOTHURN => 'Solothurn',
            self::THURGAU => 'Thurgau',
            self::URI => 'Uri',
            self::WALLIS => 'Wallis',
            self::WAADT => 'Waadt',
            self::ZUG => 'Zug',
            self::ZUERICH => 'Zürich',
            self::AUVERGNE_RHONE_ALPES => 'Auvergne-Rhône-Alpes',
            self::BOURGOGNE_FRANCHE_COMTE => 'Bourgogne-Franche-Comté',
            self::BRETAGNE => 'Bretagne',
            self::CENTRE_VAL_DE_LOIRE => 'Centre-Val de Loire',
            self::GRAND_EST => 'Grand Est',
            self::HAUTS_DE_FRANCE => 'Hauts-de-France',
            self::KORSIKA => 'Korsika',
            self::NORMANDIE => 'Normandie',
            self::NOUVELLE_AQUITAINE => 'Nouvelle-Aquitaine',
            self::OKZITANIEN => 'Okzitanien',
            self::PAYS_DE_LA_LOIRE => 'Pays de la Loire',
            self::PROVENCE_ALPES_COTE_D_AZUR => 'Provence-Alpes-Côte d\'Azur',
            self::ILE_DE_FRANCE => 'Île-de-France',
            self::EAST_MIDLANDS => 'East Midlands',
            self::EAST_OF_ENGLAND => 'East of England',
            self::LONDON => 'London',
            self::NORTH_EAST_ENGLAND => 'North East England',
            self::NORTH_WEST_ENGLAND => 'North West England',
            self::NORTHERN_IRELAND => 'Northern Ireland',
            self::SCOTLAND => 'Scotland',
            self::SOUTH_EAST_ENGLAND => 'South East England',
            self::SOUTH_WEST_ENGLAND => 'South West England',
            self::WALES => 'Wales',
            self::WEST_MIDLANDS => 'West Midlands',
            self::YORKSHIRE_AND_THE_HUMBER => 'Yorkshire and the Humber',
            self::AVEIRO => 'Aveiro',
            self::BEJA => 'Beja',
            self::BRAGA => 'Braga',
            self::BRAGANCA => 'Bragança',
            self::CASTELO_BRANCO => 'Castelo Branco',
            self::COIMBRA => 'Coimbra',
            self::FARO => 'Faro',
            self::GUARDA => 'Guarda',
            self::LEIRIA => 'Leiria',
            self::LISBOA => 'Lisboa',
            self::PORTALEGRE => 'Portalegre',
            self::PORTO => 'Porto',
            self::SANTAREM => 'Santarém',
            self::SETUBAL => 'Setúbal',
            self::VIANA_DO_CASTELO => 'Viana do Castelo',
            self::VILA_REAL => 'Vila Real',
            self::VISEU => 'Viseu',
            self::EVORA => 'Évora',
            self::BJELOVAR_BILOGORA => 'Bjelovar-Bilogora',
            self::BROD_POSAVINA => 'Brod-Posavina',
            self::DUBROVNIK_NERETVA => 'Dubrovnik-Neretva',
            self::ISTRIEN => 'Istrien',
            self::KARLOVAC => 'Karlovac',
            self::KOPRIVNICA_KRIZEVCI => 'Koprivnica-Križevci',
            self::KRAPINA_ZAGORJE => 'Krapina-Zagorje',
            self::LIKA_SENJ => 'Lika-Senj',
            self::MEDIMURJE => 'Međimurje',
            self::OSIJEK_BARANJA => 'Osijek-Baranja',
            self::POZEGA_SLAWONIEN => 'Požega-Slawonien',
            self::PRIMORJE_GORSKI_KOTAR => 'Primorje-Gorski kotar',
            self::SISAK_MOSLAVINA => 'Sisak-Moslavina',
            self::SPLIT_DALMATIEN => 'Split-Dalmatien',
            self::SIBENIK_KNIN => 'Šibenik-Knin',
            self::VARAZDIN => 'Varaždin',
            self::VIROVITICA_PODRAVINA => 'Virovitica-Podravina',
            self::VUKOVAR_SYRMIEN => 'Vukovar-Syrmien',
            self::ZADAR => 'Zadar',
            self::ZAGREB => 'Zagreb',
            self::STADT_ZAGREB => 'Stadt Zagreb',
        };
    }
}
