<?php

declare(strict_types=1);

namespace BytesCommerce\OnOffice\Attributes\Enum;

enum ObjekttypEnum: string
{
    case STELLPLATZ = 'stellplatz';
    case CARPORT = 'carport';
    case DOPPELGARAGE = 'doppelgarage';
    case DUPLEX = 'duplex';
    case TIEFGRAGE = 'tiefgarage';
    case BOOTSLIEGEPLATZ = 'bootsliegeplatz';
    case ROHDACHBODEN = 'rohdachboden';
    case SEELIEGENSCHAFT = 'seeliegenschaft';
    case JAGDREVVIER = 'jagdrevier';
    case PARKPLATZ_STROM = 'parkplatz_strom';
    case HAUSBAU_ZWEIFAMILIENHAUS = 'hausbau_zweifamilienhaus';
    case TIEFGRAGENSTELLPLATZ = 'tiefgaragenstellplatz';
    case PARKLEN_PARKHAUS = 'parken_parkhaus';
    case EINZELGARAGE = 'einzelgarage';
    case FREIZEITANLAGE = 'freizeitanlage';
    case PRAXISFLAECHE = 'praxisflaeche';
    case BUEROZENTRUM = 'buerozentrum';
    case BUNGALOW = 'bungalow';
    case EINFAMILIENHAUS_MIT_EINLIEGERWOHNUNG = 'einfamilienhausMitEinliegerwohnung';
    case ZIMMER = 'zimmer';
    case HOCHPARTERRE = 'hochparterre';
    case EIGENTUMSWOHNUNG = 'eigentumswohnung';
    case BLOCKHAUS = 'blockhaus';
    case HAUSBAU_REIHENHAUS = 'hausbau_reihenhaus';
    case HAUSBAU_MEHRFAMILIENHAUS = 'hausbau_mehrfamilienhaus';
    case HOLZHAUS = 'holzhaus';
    case FACHWERKHAUS = 'fachwerkhaus';
    case HAUSBAU_EINFAMILIENHAUS = 'hausbau_einfamilienhaus';
    case DOPPELHAUS = 'doppelhaus';
    case HAUSBAU_BUNGALOW = 'hausbau_bungalow';
    case HAUSBAU_VILLA = 'hausbau_villa';
    case MEHRFAMILIENHAUS = 'mehrfamilienhaus';
    case INDUSTRIEHALLE = 'industriehalle';
    case WOHN_UND_GESCHAEFTSHAUS = 'wohn_und_geschaeftshaus';
    case GESCHAEFTSHAUS = 'geschaeftshaus';
    case KUEHLHAUS = 'kuehlhaus';
    case BUEROGEBAEUDE = 'buerogebaeude';
    case SB_MAERKTE = 'sb_maerkte';
    case EINKAUFSCENTREN = 'einkaufscentren';
    case LAGER_MIT_FREIFLAECHE = 'lager_mit_freiflaeche';
    case LAGERFLAECHE = 'lagerflaeche';
    case WOHNANLAGEN = 'wohnanlagen';
    case VERBRAUCHERMAERKTE = 'verbrauchermaerkte';
    case SPEDITIONSLAGER = 'speditionslager';
    case INDUSTRIEANLAGEN = 'industrieanlagen';
    case ANWESEN = 'anwesen';
    case BARBETRIEB = 'barbetrieb';
    case CAFE = 'cafe';
    case LOFT = 'loft';
    case ATELIER = 'atelier';
    case BUEROETAGE = 'bueroetage';
    case BUERO_UND_LAGER = 'buero_und_lager';
    case PRAXISETAGE = 'praxisetage';
    case PRAXISHAUS = 'praxishaus';
    case AUSSTELLUNGSFLAECHE = 'ausstellungsflaeche';
    case FACTORY_OUTLET = 'factory_outlet';
    case KAUFHAUS = 'kaufhaus';
    case KIOSK = 'kiosk';
    case VERKAUFSSFLAECHE = 'verkaufssflaeche';
    case VERKAUFSHALLE = 'verkaufshalle';
    case DISKOTHEK = 'diskothek';
    case RESTAURANT = 'restaurant';
    case SPORTANLAGE = 'sportanlage';
    case VERGNUEGUNGSPARKS_UND_CENTER = 'vergnuegungsparks_und_center';
    case HALLE = 'halle';
    case WERKSTATT = 'werkstatt';
    case HOCHREGALLAGER = 'hochregallager';
    case SERVICE = 'service';
    case DACHGESCHOSS = 'dachgeschoss';
    case MAISONETTE = 'maisonette';
    case LOFT_STUDIO_ATELIER = 'loft-studio-atelier';
    case PENTHOUSE = 'penthouse';
    case TERRASSEN = 'terrassen';
    case ETAGE = 'etage';
    case ERDGESCHOSS = 'erdgeschoss';
    case REIHENHAUS = 'reihenhaus';
    case REIHENMITTEL = 'reihenmittel';
    case REIHENECK = 'reiheneck';
    case DOPPELHAUSHAELFTE = 'doppelhaushaelfte';
    case EINFAMILIENHAUS = 'einfamilienhaus';
    case VILLA = 'villa';
    case BAUERNHAUS = 'bauernhaus';
    case SCHLOSS = 'schloss';
    case ZWEIFAMILIENHAUS = 'zweifamilienhaus';
    case WOHNEN = 'wohnen';
    case GEWERBE = 'gewerbe';
    case INDUSTRIE = 'industrie';
    case LAND_FORSTWIRTSCHAFT = 'land_forstwirtschaft';
    case BUEROFLAECHE = 'bueroflaeche';
    case BUEROHAUS = 'buerohaus';
    case PRAXIS = 'praxis';
    case LADENLOKAL = 'ladenlokal';
    case EINKAUFSZENTRUM = 'einkaufszentrum';
    case PENSIONEN = 'pensionen';
    case HOTELS = 'hotels';
    case BAUERNHOF = 'bauernhof';
    case REITERHOEFE = 'reiterhoefe';
    case PARKHAUS = 'parkhaus';
    case TANKSTELLE = 'tankstelle';
    case SONSTIGE = 'sonstige';
    case GEWERBEEINHEIT = 'gewerbeeinheit';
    case GEWERBEANWESEN = 'gewerbeanwesen';
    case APPARTMENT = 'appartment';
    case BESONDERE_IMMOBILIE = 'besondereImmobilie';

    public function label(): string
    {
        return match ($this) {
            self::STELLPLATZ => 'Stellplatz',
            self::CARPORT => 'Carport',
            self::DOPPELGARAGE => 'Doppelgarage',
            self::DUPLEX => 'Duplex',
            self::TIEFGRAGE => 'Tiefgarage',
            self::BOOTSLIEGEPLATZ => 'Bootsliegeplatz',
            self::ROHDACHBODEN => 'Rohdachboden',
            self::SEELIEGENSCHAFT => 'Seeliegenschaft',
            self::JAGDREVVIER => 'Jagdrevier',
            self::PARKPLATZ_STROM => 'Parkplatz mit Strom',
            self::HAUSBAU_ZWEIFAMILIENHAUS => 'Zweifamilienhaus',
            self::TIEFGRAGENSTELLPLATZ => 'Tiefgaragenstellplatz',
            self::PARKLEN_PARKHAUS => 'Parkhaus',
            self::EINZELGARAGE => 'Einzelgarage',
            self::FREIZEITANLAGE => 'Freizeitanlage',
            self::PRAXISFLAECHE => 'Praxisfläche',
            self::BUEROZENTRUM => 'Bürozentrum',
            self::BUNGALOW => 'Bungalow',
            self::EINFAMILIENHAUS_MIT_EINLIEGERWOHNUNG => 'Einfamilienhaus mit Einliegerwohnung',
            self::ZIMMER => 'Zimmer',
            self::HOCHPARTERRE => 'Hochparterre',
            self::EIGENTUMSWOHNUNG => 'Eigentumswohnung',
            self::BLOCKHAUS => 'Blockhaus',
            self::HAUSBAU_REIHENHAUS => 'Reihenhaus',
            self::HAUSBAU_MEHRFAMILIENHAUS => 'Mehrfamilienhaus',
            self::HOLZHAUS => 'Holzhaus',
            self::FACHWERKHAUS => 'Fachwerkhaus',
            self::HAUSBAU_EINFAMILIENHAUS => 'Einfamilienhaus',
            self::DOPPELHAUS => 'Doppelhaus',
            self::HAUSBAU_BUNGALOW => 'Bungalow',
            self::HAUSBAU_VILLA => 'Villa',
            self::MEHRFAMILIENHAUS => 'Mehrfamilienhaus',
            self::INDUSTRIEHALLE => 'Industriehalle',
            self::WOHN_UND_GESCHAEFTSHAUS => 'Wohn- und Geschäftshaus',
            self::GESCHAEFTSHAUS => 'Geschäftshaus',
            self::KUEHLHAUS => 'Kühlhaus',
            self::BUEROGEBAEUDE => 'Bürogebäude',
            self::SB_MAERKTE => 'SB Märkte',
            self::EINKAUFSCENTREN => 'Einkaufscentren',
            self::LAGER_MIT_FREIFLAECHE => 'Lager mit Freifläche',
            self::LAGERFLAECHE => 'Lagerfläche',
            self::WOHNANLAGEN => 'Wohnanlagen',
            self::VERBRAUCHERMAERKTE => 'Verbrauchermärkte',
            self::SPEDITIONSLAGER => 'Speditionslager',
            self::INDUSTRIEANLAGEN => 'Industrieanlagen',
            self::ANWESEN => 'Anwesen',
            self::BARBETRIEB => 'Barbetrieb',
            self::CAFE => 'Café',
            self::LOFT => 'Loft',
            self::ATELIER => 'Atelier',
            self::BUEROETAGE => 'Büroetage',
            self::BUERO_UND_LAGER => 'Büro und Lagergebäude',
            self::PRAXISETAGE => 'Praxisetage',
            self::PRAXISHAUS => 'Praxishaus',
            self::AUSSTELLUNGSFLAECHE => 'Ausstellungsfläche',
            self::FACTORY_OUTLET => 'Factory Outlet',
            self::KAUFHAUS => 'Kaufhaus',
            self::KIOSK => 'Kiosk',
            self::VERKAUFSSFLAECHE => 'Verkaufsfläche',
            self::VERKAUFSHALLE => 'Verkaufshalle',
            self::DISKOTHEK => 'Diskothek',
            self::RESTAURANT => 'Restaurant',
            self::SPORTANLAGE => 'Sportanlage',
            self::VERGNUEGUNGSPARKS_UND_CENTER => 'Vergnügungsparks und Center',
            self::HALLE => 'Halle',
            self::WERKSTATT => 'Werkstatt',
            self::HOCHREGALLAGER => 'Hochregallager',
            self::SERVICE => 'Service',
            self::DACHGESCHOSS => 'Dachgeschoss',
            self::MAISONETTE => 'Maisonette',
            self::LOFT_STUDIO_ATELIER => 'Loft/Studio/Atelier',
            self::PENTHOUSE => 'Penthouse',
            self::TERRASSEN => 'Terrasse',
            self::ETAGE => 'Etagenwohnung',
            self::ERDGESCHOSS => 'Erdgeschoss',
            self::REIHENHAUS => 'Reihenhaus',
            self::REIHENMITTEL => 'Reihenmittel',
            self::REIHENECK => 'Reiheneck',
            self::DOPPELHAUSHAELFTE => 'Doppelhaushälfte',
            self::EINFAMILIENHAUS => 'Einfamilienhaus',
            self::VILLA => 'Villa',
            self::BAUERNHAUS => 'Bauernhaus',
            self::SCHLOSS => 'Schloss',
            self::ZWEIFAMILIENHAUS => 'Zweifamilienhaus',
            self::WOHNEN => 'Wohnen',
            self::GEWERBE => 'Gewerbe',
            self::INDUSTRIE => 'Industrie',
            self::LAND_FORSTWIRTSCHAFT => 'Land/Forstwirtschaft',
            self::BUEROFLAECHE => 'Bürofläche',
            self::BUEROHAUS => 'Bürohaus',
            self::PRAXIS => 'Praxis',
            self::LADENLOKAL => 'Ladenlokal',
            self::EINKAUFSZENTRUM => 'Einkaufszentrum',
            self::PENSIONEN => 'Pension',
            self::HOTELS => 'Hotels',
            self::BAUERNHOF => 'Bauernhof',
            self::REITERHOEFE => 'Reiterhöfe',
            self::PARKHAUS => 'Parkhaus',
            self::TANKSTELLE => 'Tankstelle',
            self::SONSTIGE => 'Sonstige',
            self::GEWERBEEINHEIT => 'Gewerbeeinheit',
            self::GEWERBEANWESEN => 'Gewerbeanwesen',
            self::APPARTMENT => 'Apartment',
            self::BESONDERE_IMMOBILIE => 'besondere Immobilie',
        };
    }
}
